#!/bin/sh

SYS_KEY=/sys/class/backlight/intel_backlight/brightness

CURRENT=$(cat $SYS_KEY)

case $1 in 
    -inc) 
        NEW=$((1 + $CURRENT * (100 + $2)/100)) 
        ;; 
    -dec) 
        NEW=$((1 + $CURRENT * (100 - $2)/100)) 
        ;; 
    *) echo "Don't get it, sorry" 
        exit 10 
        ;;  
esac

sudo /bin/sh -c "echo $NEW | tee $SYS_KEY"
